//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyGaraOto.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class THAMSO
    {
        public int MaThamSo { get; set; }
        public Nullable<bool> SoTienThu { get; set; }
        public Nullable<int> XeToiDa { get; set; }
        public Nullable<double> PhanTram { get; set; }
        public Nullable<int> ThangBaoCao { get; set; }
    }
}
