CREATE DATABASE GARAGE_MANAGEMENT
USE GARAGE_MANAGEMENT

CREATE TABLE XE (
	BienSo			NVARCHAR(20),
	TenChuXe		NVARCHAR(MAX),
	DienThoai		NVARCHAR(20),
	DiaChi			NVARCHAR(MAX),
	Email			NVARCHAR(MAX),
	NgayTiepNhan	SMALLDATETIME,
	MaHieuXe		INT,
	TienNo			MONEY DEFAULT 0

	CONSTRAINT XE_PK PRIMARY KEY (BienSo)
)

CREATE TABLE HIEUXE (
	MaHieuXe	INT IDENTITY (1, 1),
	TenHieuXe	VARCHAR

	CONSTRAINT HIEUXE_PK PRIMARY KEY (MaHieuXe)
)

CREATE TABLE PHIEUSUACHUA (
	MaPhieuSC	INT IDENTITY (1, 1),
	BienSo		NVARCHAR(20),
	NgaySuaChua	SMALLDATETIME,
	TongTien	MONEY DEFAULT 0

	CONSTRAINT PHIEUSUACHUA_PK PRIMARY KEY (MaPhieuSC)
)

CREATE TABLE CT_PSC (
	MaCTPSC		INT IDENTITY (1, 1),
	MaPhieuSC	INT,
	NoiDung		NVARCHAR(MAX),
	SoLan		INT DEFAULT 1,
	MaTienCong	INT,
	ThanhTien	MONEY DEFAULT 0

	CONSTRAINT CT_PSC_PK PRIMARY KEY (MaCTPSC)
)

CREATE TABLE CT_SUDUNGVATTU (
	MaCTPSC		INT,
	MaVatTu		INT,
	SoLuong		INT,
	DonGia		MONEY DEFAULT 0,
	ThanhTien	MONEY DEFAULT 0

	CONSTRAINT CT_SUDUNGVATTU_PK PRIMARY KEY (MaCTPSC, MaVatTu)
)

CREATE TABLE VATTU (
	MaVatTu			INT IDENTITY (1, 1),
	TenVatTu		NVARCHAR(MAX),
	DonGiaHienTai	MONEY DEFAULT 0,
	SoLuongTon		INT

	CONSTRAINT VATTU_PK PRIMARY KEY (MaVatTu)
)

CREATE TABLE TIENCONG (
	MaTienCong	INT IDENTITY (1, 1),
	TenTienCong	NVARCHAR(MAX),
	GiaTienCong	MONEY DEFAULT 0

	CONSTRAINT TIENCONG_PK PRIMARY KEY (MaTienCong)
)

CREATE TABLE PHIEUTHUTIEN (
	MaPTT		INT IDENTITY (1, 1),
	BienSo		NVARCHAR(20),
	NgayThuTien SMALLDATETIME,
	SoTienThu	MONEY 

	CONSTRAINT PHIEUTHUTIEN_PK PRIMARY KEY (MaPTT)
)

CREATE TABLE PHIEUNHAP (
	MaPhieuNhap	INT IDENTITY (1, 1),
	NgayNhap	SMALLDATETIME,
	ThanhTien	MONEY DEFAULT 0

	CONSTRAINT PHIEUNHAP_PK PRIMARY KEY (MaPhieuNhap)
)

CREATE TABLE CT_PHIEUNHAP (
	MaPhieuNhap	INT,
	MaVatTu		INT,
	SoLuong		INT,
	DonGiaNhap	MONEY,
	DonGiaBan	MONEY,
	ThanhTien	MONEY,
	CONSTRAINT CT_PNVT_PK PRIMARY KEY (MaPhieuNhap, MaVatTu)
)

CREATE TABLE BAOCAOTON (
	MaBCT		INT IDENTITY (1, 1),
	MaVatTu		INT,
	ThoiGian	SMALLDATETIME, -- ngay minh muon xem bao cao ton
	TonDau		INT,
	PhatSinh	INT,
	TonCuoi		INT,

	CONSTRAINT BAOCAOTON_PK PRIMARY KEY (MaBCT)
)


CREATE TABLE BAOCAODOANHSO (
	MaBCDS			INT IDENTITY (1, 1),
	ThoiGian		SMALLDATETIME, -- ngay minh muon xem bao cao doanh so
	TongDoanhThu	MONEY

	CONSTRAINT BAOCAODOANHSO_PK PRIMARY KEY (MaBCDS)
)

CREATE TABLE CT_BCDS (
	MaBCDS		INT,
	MaHieuXe	INT,
	SoLuotSua	INT,
	ThanhTien	MONEY,
	TiLe		VARCHAR(MAX)

	CONSTRAINT CT_BCDS_PK PRIMARY KEY (MaBCDS, MaHieuXe)
)

CREATE TABLE THAMSO (
	TenThamSo	NVARCHAR(20) PRIMARY KEY,
	GiaTri		INT
)

CREATE TABLE TAIKHOAN (
	MaTaiKhoan	INT IDENTITY (1, 1) PRIMARY KEY,
	TenTaiKhoan	NVARCHAR(MAX),
	MatKhau		NVARCHAR(MAX),
	QuyenHan	INT
)

CREATE TABLE VAITRO (
	MaVaiTro	INT PRIMARY KEY,
	TenVaiTro	NVARCHAR(20)
)

ALTER TABLE XE ADD CONSTRAINT FK_XE_MaHieuXe FOREIGN KEY (MaHieuXe) REFERENCES HIEUXE(MaHieuXe)
ALTER TABLE PHIEUSUACHUA ADD CONSTRAINT FK_PSC_BienSo FOREIGN KEY (BienSo) REFERENCES XE(BienSo)
ALTER TABLE CT_PSC ADD CONSTRAINT FK_MaPhieuSC FOREIGN KEY (MaPhieuSC) REFERENCES PHIEUSUACHUA(MaPhieuSC)
ALTER TABLE CT_PSC ADD CONSTRAINT FK_MaTienCong FOREIGN KEY (MaTienCong) REFERENCES TIENCONG(MaTienCong)
ALTER TABLE CT_SUDUNGVATTU ADD CONSTRAINT FK_MaCTPSC FOREIGN KEY (MaCTPSC) REFERENCES CT_PSC (MaCTPSC)
ALTER TABLE CT_SUDUNGVATTU ADD CONSTRAINT FK_SDVT_MaVatTu FOREIGN KEY (MaVatTu) REFERENCES VATTU(MaVatTu)
ALTER TABLE PHIEUTHUTIEN ADD CONSTRAINT FK_PTT_BienSo FOREIGN KEY (BienSo) REFERENCES XE(BienSo)
ALTER TABLE CT_PHIEUNHAP ADD CONSTRAINT FK_MaPhieuNhap FOREIGN KEY (MaPhieuNhap) REFERENCES PHIEUNHAP(MaPhieuNhap)
ALTER TABLE CT_PHIEUNHAP ADD CONSTRAINT FK_PNVT_MaVatTu FOREIGN KEY (MaVatTu) REFERENCES VATTU(MaVatTu)
ALTER TABLE BAOCAOTON ADD CONSTRAINT FK_BCT_MaVatTu FOREIGN KEY (MaVatTu) REFERENCES VATTU(MaVatTu)
ALTER TABLE CT_BCDS ADD CONSTRAINT FK_MaBCDS FOREIGN KEY (MaBCDS) REFERENCES BAOCAODOANHSO(MaBCDS)
ALTER TABLE CT_BCDS ADD CONSTRAINT FK_CT_BCDS_MaHieuXe FOREIGN KEY (MaHieuXe) REFERENCES HIEUXE(MaHieuXe)
ALTER TABLE TAIKHOAN ADD CONSTRAINT FK_QuyenHan FOREIGN KEY (QuyenHan) REFERENCES VAITRO(MaVaiTro)


INSERT INTO VAITRO VALUES (0, 'staff')
INSERT INTO VAITRO VALUES (1, 'admin')

INSERT INTO TAIKHOAN (TenTaiKhoan, MatKhau, QuyenHan) VALUES ('staff', '978aae9bb6bee8fb75de3e4830a1be46', 0)
INSERT INTO TAIKHOAN (TenTaiKhoan, MatKhau, QuyenHan) VALUES ('admin', 'db69fc039dcbd2962cb4d28f5891aae1', 1)

