DROP TABLE IF EXISTS GARAGE_MANAGEMENT
CREATE DATABASE GARAGE_MANAGEMENT
USE GARAGE_MANAGEMENT

CREATE TABLE XE (
	BienSo			NVARCHAR(20),
	TenChuXe		NVARCHAR(MAX),
	DienThoai		NVARCHAR(20),
	DiaChi			NVARCHAR(MAX),
	Email			NVARCHAR(MAX),
	NgayTiepNhan	SMALLDATETIME,
	MaHieuXe		INT,
	TienNo			MONEY DEFAULT 0,
	CONSTRAINT XE_PK PRIMARY KEY (BienSo)
)

CREATE TABLE HIEUXE (
	MaHieuXe	INT IDENTITY (1, 1),
	TenHieuXe	NVARCHAR(MAX)

	CONSTRAINT HIEUXE_PK PRIMARY KEY (MaHieuXe)
)

CREATE TABLE PHIEUSUACHUA (
	MaPhieuSC	INT IDENTITY (1, 1),
	BienSo		NVARCHAR(20),
	NgaySuaChua	SMALLDATETIME,
	TongTien	MONEY DEFAULT 0

	CONSTRAINT PHIEUSUACHUA_PK PRIMARY KEY (MaPhieuSC)
)

CREATE TABLE CT_PSC (
	MaCTPSC		INT IDENTITY (1, 1),
	MaPhieuSC	INT,
	NoiDung		NVARCHAR(MAX),
	SoLan		INT DEFAULT 1,
	MaTienCong	INT,
	ThanhTien	MONEY DEFAULT 0

	CONSTRAINT CT_PSC_PK PRIMARY KEY (MaCTPSC)
)

CREATE TABLE CT_SUDUNGVATTU (
	MaCTPSC		INT,
	MaVatTu		INT,
	SoLuong		INT,
	DonGia		MONEY DEFAULT 0,
	ThanhTien	MONEY DEFAULT 0

	CONSTRAINT CT_SUDUNGVATTU_PK PRIMARY KEY (MaCTPSC, MaVatTu)
)

CREATE TABLE VATTU (
	MaVatTu			INT IDENTITY (1, 1),
	TenVatTu		NVARCHAR(MAX),
	DonGiaHienTai	MONEY DEFAULT 0,
	SoLuongTon		INT

	CONSTRAINT VATTU_PK PRIMARY KEY (MaVatTu)
)

CREATE TABLE TIENCONG (
	MaTienCong	INT IDENTITY (1, 1),
	TenTienCong	NVARCHAR(MAX),
	GiaTienCong	MONEY DEFAULT 0

	CONSTRAINT TIENCONG_PK PRIMARY KEY (MaTienCong)
)

CREATE TABLE PHIEUTHUTIEN (
	MaPTT		INT IDENTITY (1, 1),
	BienSo		NVARCHAR(20),
	NgayThuTien SMALLDATETIME,
	SoTienThu	MONEY 

	CONSTRAINT PHIEUTHUTIEN_PK PRIMARY KEY (MaPTT)
)

CREATE TABLE PHIEUNHAP (
	MaPhieuNhap	INT IDENTITY (1, 1),
	NgayNhap	SMALLDATETIME,
	ThanhTien	MONEY DEFAULT 0

	CONSTRAINT PHIEUNHAP_PK PRIMARY KEY (MaPhieuNhap)
)

CREATE TABLE CT_PHIEUNHAP (
	MaPhieuNhap	INT,
	MaVatTu		INT,
	SoLuong		INT,
	DonGiaNhap	MONEY,
	DonGiaBan	MONEY,
	ThanhTien	MONEY,
	CONSTRAINT CT_PNVT_PK PRIMARY KEY (MaPhieuNhap, MaVatTu)
)

CREATE TABLE BAOCAOTON (
	MaBCT		INT IDENTITY (1, 1),
	MaVatTu		INT,
	ThoiGian	SMALLDATETIME, -- ngay minh muon xem bao cao ton
	TonDau		INT DEFAULT 0,
	PhatSinh	INT DEFAULT 0,
	TonCuoi		INT DEFAULT 0,

	CONSTRAINT BAOCAOTON_PK PRIMARY KEY (MaBCT)
)

CREATE TABLE BAOCAODOANHSO (
	MaBCDS			INT IDENTITY (1, 1),
	ThoiGian		SMALLDATETIME, -- ngay minh muon xem bao cao doanh so
	TongDoanhThu	MONEY DEFAULT 0

	CONSTRAINT BAOCAODOANHSO_PK PRIMARY KEY (MaBCDS)
)

CREATE TABLE CT_BCDS (
	MaBCDS		INT,
	MaHieuXe	INT,
	SoLuotSua	INT DEFAULT 0,
	ThanhTien	MONEY DEFAULT 0,
	TiLe		VARCHAR(MAX)

	CONSTRAINT CT_BCDS_PK PRIMARY KEY (MaBCDS, MaHieuXe)
)

CREATE TABLE THAMSO (
	MaThamSo	INT PRIMARY KEY,
	SoTienThu	BIT,
	XeToiDa		INT,
	PhanTram	FLOAT,
	ThangBaoCao INT
)

CREATE TABLE TAIKHOAN (
	MaTaiKhoan	INT IDENTITY (1, 1) PRIMARY KEY,
	TenTaiKhoan	NVARCHAR(MAX),
	MatKhau		NVARCHAR(MAX),
	HoTen		NVARCHAR(MAX),
	NgaySinh	SMALLDATETIME,
	Email		NVARCHAR(MAX),
	QuyenHan	INT
)

CREATE TABLE VAITRO (
	MaVaiTro	INT PRIMARY KEY,
	TenVaiTro	NVARCHAR(20),
)

ALTER TABLE XE ADD CONSTRAINT FK_XE_MaHieuXe FOREIGN KEY (MaHieuXe) REFERENCES HIEUXE(MaHieuXe)
ALTER TABLE PHIEUSUACHUA ADD CONSTRAINT FK_PSC_BienSo FOREIGN KEY (BienSo) REFERENCES XE(BienSo)
ALTER TABLE CT_PSC ADD CONSTRAINT FK_MaPhieuSC FOREIGN KEY (MaPhieuSC) REFERENCES PHIEUSUACHUA(MaPhieuSC)
ALTER TABLE CT_PSC ADD CONSTRAINT FK_MaTienCong FOREIGN KEY (MaTienCong) REFERENCES TIENCONG(MaTienCong)
ALTER TABLE CT_SUDUNGVATTU ADD CONSTRAINT FK_MaCTPSC FOREIGN KEY (MaCTPSC) REFERENCES CT_PSC (MaCTPSC)
ALTER TABLE CT_SUDUNGVATTU ADD CONSTRAINT FK_SDVT_MaVatTu FOREIGN KEY (MaVatTu) REFERENCES VATTU(MaVatTu)
ALTER TABLE PHIEUTHUTIEN ADD CONSTRAINT FK_PTT_BienSo FOREIGN KEY (BienSo) REFERENCES XE(BienSo)
ALTER TABLE CT_PHIEUNHAP ADD CONSTRAINT FK_MaPhieuNhap FOREIGN KEY (MaPhieuNhap) REFERENCES PHIEUNHAP(MaPhieuNhap)
ALTER TABLE CT_PHIEUNHAP ADD CONSTRAINT FK_PNVT_MaVatTu FOREIGN KEY (MaVatTu) REFERENCES VATTU(MaVatTu)
ALTER TABLE BAOCAOTON ADD CONSTRAINT FK_BCT_MaVatTu FOREIGN KEY (MaVatTu) REFERENCES VATTU(MaVatTu)
ALTER TABLE CT_BCDS ADD CONSTRAINT FK_MaBCDS FOREIGN KEY (MaBCDS) REFERENCES BAOCAODOANHSO(MaBCDS)
ALTER TABLE CT_BCDS ADD CONSTRAINT FK_CT_BCDS_MaHieuXe FOREIGN KEY (MaHieuXe) REFERENCES HIEUXE(MaHieuXe)
ALTER TABLE TAIKHOAN ADD CONSTRAINT FK_QuyenHan FOREIGN KEY (QuyenHan) REFERENCES VAITRO(MaVaiTro)

SET DATEFORMAT DMY

INSERT INTO VAITRO VALUES (0, 'staff')
INSERT INTO VAITRO VALUES (1, 'admin')

INSERT INTO TAIKHOAN (TenTaiKhoan, MatKhau, QuyenHan) VALUES ('staff', '978aae9bb6bee8fb75de3e4830a1be46', 0)
INSERT INTO TAIKHOAN (TenTaiKhoan, MatKhau, QuyenHan) VALUES ('admin', 'db69fc039dcbd2962cb4d28f5891aae1', 1)

-- Co the them vao truoc
INSERT INTO HIEUXE (TenHieuXe) VALUES ('Lamborghini')
INSERT INTO HIEUXE (TenHieuXe) VALUES ('VinFast')
INSERT INTO HIEUXE (TenHieuXe) VALUES ('Mazda')
INSERT INTO HIEUXE (TenHieuXe) VALUES ('Toyota')
INSERT INTO HIEUXE (TenHieuXe) VALUES ('Mercedes-benz')
INSERT INTO HIEUXE (TenHieuXe) VALUES ('Lexus')
INSERT INTO HIEUXE (TenHieuXe) VALUES ('Ford')
INSERT INTO HIEUXE (TenHieuXe) VALUES ('Hyundai')
INSERT INTO HIEUXE (TenHieuXe) VALUES ('Porsche')
INSERT INTO HIEUXE (TenHieuXe) VALUES ('Honda')
INSERT INTO HIEUXE (TenHieuXe) VALUES ('Bentley')
INSERT INTO HIEUXE (TenHieuXe) VALUES ('BMW')
INSERT INTO HIEUXE (TenHieuXe) VALUES ('Audi')
INSERT INTO HIEUXE (TenHieuXe) VALUES ('Bugatti')
INSERT INTO HIEUXE (TenHieuXe) VALUES ('Ferrari')

-- Co the them vao truoc
INSERT INTO VATTU (TenVatTu, DonGiaHienTai, SoLuongTon) VALUES 
	(N'Dây curoa máy', '300000', '10'),
	(N'Dây curoa cam', '3000000', '10'),
	(N'Lọc gió điều hòa', '2500000', '10'),
	(N'Lọc gió động cơ', '2000000', '10'),
	(N'Lọc nhiên liệu', '4000000', '10'),
	(N'Lọc nhớt động cơ', '3300000', '10'),
	(N'Đĩa ly hợp', '3500000', '10'),
	(N'Má phanh', '1500000', '10'),
	(N'Chổi gạt nước', '2500000', '10'),
	(N'Bugi', '500000', '10'),
	(N'Bộ khởi động', '3000000', '10'),
	(N'Máy nén', '6000000', '10'),
	(N'Bơm nhiên liệu', '4000000', '10'),
	(N'Đèn pha', '2000000', '10'),
	(N'Đèn xi nhan', '500000', '10'),
	(N'Đèn hậu', '3000000', '10'),
	(N'Đèn sương mù', '6000000', '10'),
	(N'Bơm nhiên liệu', '4000000', '10');

INSERT INTO TIENCONG (TenTienCong, GiaTienCong) VALUES
	(N'Rửa xe', '300000'),
	(N'Phủ Ceramic', '3000000'),
	(N'Phủ thuỷ tinh', '2500000'),
	(N'Vệ sinh xe cao cấp', '2000000'),
	(N'Phủ gầm chống ồn chống gỉ', '4000000'),
	(N'Đánh bóng, hiệu chỉnh mặt sơn', '3300000'),
	(N'Sơn công nghệ cao', '3500000'),
	(N'Gò phục hồi thân vỏ', '1500000'),
	(N'Bảo dưỡng định kỳ', '2500000'),
	(N'Kiểm tra tình trạng xe', '500000'),
	(N'Sửa chữa Động cơ – Hộp số', '3000000'),
	(N'Sửa chữa gầm bệ', '6000000'),
	(N'Sửa chữa hệ thống điện', '4000000'),
	(N'Dán phim cách nhiệt', '2000000');

INSERT INTO THAMSO (MaThamSo, SoTienThu, XeToiDa, PhanTram) VALUES (0, 1, 30, 0.2)

